### ISSUE TITLE
Enable reCAPTCHA

### ISSUE THREAD

**Issue by VincentTam** [m-cat/bytedude.com#44]
To prevent spam comments.  Related issue: https://github.com/eduardoboucas/staticman/issues/175.

**Comment by m-cat** [comment]
1. reCAPTCHA does not work for many users, including some Firefox users, some VPN users, and Tor users.
2. Google is evil.

**Comment by m-cat** [comment]
Thanks for writing up the issue though. Luckily the spammers aren't really bothering me so far.

**Comment by VincentTam** [comment]
> * reCAPTCHA does not work for many users, including some Firefox users, some VPN users, and Tor users.
> * Google is evil.

Good point!  I had forgotten the VPN users.  Thanks for reminding me that.
